notifications:
  email: false

# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

env:
  global:
    # CODECLIMATE_REPO_TOKEN
    - secure: BNxQea3NC+Aorbb/9xCkWIlI4ZRLmY1yzKBSmK6O66JlbLGAdYnABoGc7mmAzP3xWIVNlga5BFzvOiySGU40kvezfGth7Aph7PzlSHtDgMp0naHuUMxbWd5OtzrAVVpEUMPDqQY61J2uq7exn5EQvgqsCkTHy/Bfo5+mFzYxtb0Q0rEYkMXqvRMab8dmhUdGEjInMWV/2BUu26uhVslRUlBbYScx5o2RFpDQ2oBEWIGGEfOCzqOFWgpwp+hc8tLkA3Vt0EWX2I2U1IJ+x+v8VApY/rVKEhmsN2vgrbVpQEUz23jpWQcWSSmUTj2ld3NP/+WNOcNPJH1EvSQRDFQtUwFAzUAPJwNY2r7XBJV243480mIyldHFyGkuNbqn5q74hiStniik8OjC1wvxoJZ59VJjFSFrGpfhjV+lCbkDHgevztE+MpzWhAqGqUFXCaVI1QipAVd8F+CBXd0ulpRETG03ZnAKv+x9i+PNyLKcK7FfxN2DJUDHgrv6EhiqeJWOX/EeNH9hJKIu0lAh1J0fKQRs2zigiceFQiEEMWbA94mCBztx0psL6gBHWqsXpgvFH4IUx33COqzqlGyllebQcKiIzdhVrnyDllOr5hOgjVNJ5drc188nVxTpcZANCMT9CClsvZC20dYFxv4bpOTRv2fXPLlpHMPPCH5C8XHQvyY=

# Language options
language: node_js
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
node_js:
  - "0"
  - 4
  - 5
before_script:
  - npm prune
script:
  - npm run cover
  - npm run lint

# Npm publish options
before_deploy:
  - npm run build
deploy:
  skip_cleanup: true # keep the devDependencies
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: AlmzrymfDLf/QSxufAbmRJH8IJQZa7vHn5LgnQWvLwTz6oEzrF08DoTUlCwji/ta+xcEB6Az2UO8S03jGwiHSkTJ5pIPaEQJ0+i//Hiin5ZFoHBVePp/D6se8LlT/GyGVihAUeAleliHCay6E59FWeh4h/2xE/zGo6eY9C4+3gSPNgl6ZhPOnZdawu8B4RpBZz7kgeRuUh1I8GFSnGZSSgh6WdbAk2ev8hsniuDhd4FggbJ/y/UST+ml3sHO0j2MJATLunUgGS92FbjKRhYqjccGTKjovvlxoiUA0fpqmHwOAhciO/Bm6zngA52aPWtGAmY+XLndMck/sTGPzwHtIFiCMaild+0bvXFvfyh/h/2QdbPvKjNpMNJtpUe2pPbQNPMqz8oGE33Y6eejFjVMF5xe/mf1AF1CItn+0T9sioD54b/hAb5xWf+2F1BR3R8yyW9PTRm9/CEJnz4kVDkyfAahr2R3LGXG4lneIOXGc1hoRz6Tfg7mSXRp02xpNQzMzsld9dkL7k1vdyjZXtbM3sBrBSIykdoaR5tIwUIXxXQZplHjOGHpiH0c7bp65oQW18NTfVuiuQp/kgXjnIQTX30r7RQ9WXtLV45if2s9M0KK8kCWXjyiIqe7CwTiVOyWVKeLHqgDmK/p8kfpiSKMAeAbzbafbku6oigmReQUCfc=
  on:
    node: 4
